imagePullPolicy: IfNotPresent

bootnode:
  replicas: 2
  image:
    repository: ethereum/client-go
    tag: alltools-v1.10.6

bootnodeRegistrar:
  replicas: 1
  image:
    repository: jpoon/bootnode-registrar
    tag: v1.0.0

geth:
  image:
    repository: ethereum/client-go
    tag: v1.10.6
  tx:
    replicas: 1
    service:
      type: ClusterIP
  miner:
    replicas: 2
    account:
      secret: ""
  genesis:
    networkId: 1337