apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-registrar
  labels:
    app: node-registrar
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.bootnodeRegistrar.replicas }}
  selector:
    matchLabels:
      app: node-registrar
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: node-registrar
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: node-registrar
        image: {{ .Values.bootnodeRegistrar.image.repository }}:{{ .Values.bootnodeRegistrar.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: BOOTNODE_SERVICE
          value: {{ template "ethereum.fullname" . }}-bootnode-service.{{ .Release.Namespace }}.svc.cluster.local
        ports:
          - name: node-registrar
            containerPort: 9898
